import { Product, RelatedProduct, Feature } from './types';

export const MAIN_PRODUCT: Product = {
  id: 'gk61-keyboard',
  name: 'GK61 Mechanical Keyboard RGB 60% Hot-Swappable for Gaming',
  badge: '100% New - 2-Year Warranty',
  rating: 4.5,
  reviewsCount: 742,
  currentPrice: 25.28,
  oldPrice: 39.19,
  discount: 60,
  savings: 298.35, // This value from the HTML seems inconsistent with the prices, but I'll keep it as requested.
  images: [
    'Produit/Produit1.jpg',
    'Produit/Produit2.jpg',
    'Produit/Produit3.jpg',
    'Produit/Produit4.jpg',
  ],
};

export const RELATED_PRODUCTS: RelatedProduct[] = [
  {
    id: '1',
    name: 'Razer Deathadder v3 Hyperspeed',
    image: 'Produit/similar1.jpg',
    rating: 4.7,
    oldPrice: 99.99,
    currentPrice: 81.99,
    soldCount: 1250,
    discount: 18,
  },
  {
    id: '2',
    name: 'Arctis Nova Pro Wireless for Xbox & PC',
    image: 'Produit/similar2.jpg',
    rating: 5.0,
    oldPrice: 379.99,
    currentPrice: 227.99,
    soldCount: 2150,
    discount: 40,
  },
  {
    id: '3',
    name: 'SteelSeries Apex Pro TKL (Gen 3)',
    image: 'Produit/similar3.jpg',
    rating: 4.9,
    oldPrice: 259.00,
    currentPrice: 207.2,
    soldCount: 1180,
    discount: 20,
  },
  {
    id: '4',
    name: 'Secretlab Titan Evo Nanogen',
    image: 'Produit/similar4.jpg',
    rating: 4.9,
    oldPrice: 799.00,
    currentPrice: 624.00,
    soldCount: 1520,
    discount: 22,
  },
  {
    id: '5',
    name: 'Xbox Core Controller (Carbon Black)',
    image: 'Produit/similar5.jpg',
    rating: 4.6,
    oldPrice: 59.00,
    currentPrice: 50.74,
    soldCount: 910,
    discount: 14,
  },
  {
    id: '6',
    name: 'HyperX QuadCast S',
    image: 'Produit/similar6.jpg',
    rating: 4.8,
    oldPrice: 159.00,
    currentPrice: 135.00,
    soldCount: 740,
    discount: 15,
  },
  {
    id: '7',
    name: 'Secretlab Magnus Pro',
    image: 'Produit/similar7.jpg',
    rating: 4.9,
    oldPrice: 259.00,
    currentPrice: 207.20,
    soldCount: 1180,
    discount: 20,
  },
  {
    id: '8',
    name: 'Asus ROG Rapture GT-BE98 Pro',
    image: 'Produit/similar8.jpg',
    rating: 4.9,
    oldPrice: 949.99,
    currentPrice: 493.99,
    soldCount: 1520,
    discount: 22,
  },
  {
    id: '9',
    name: 'SteelSeries Arctis GameBuds - White',
    image: 'Produit/similar9.jpg',
    rating: 4.6,
    oldPrice: 199.00,
    currentPrice: 117.99,
    soldCount: 910,
    discount: 41,
  },
  {
    id: '10',
    name: 'Gigabyte Aorus FO32U2 Pro',
    image: 'Produit/similar10.jpg',
    rating: 4.8,
    oldPrice: 1624.99,
    currentPrice: 1056.25,
    soldCount: 740,
    discount: 15,
  },
];

export const FEATURES: Feature[] = [
  {
    title: 'Hot-Swappable Switches',
    description: 'Allows switching switches without soldering – compatible with Gateron, Kailh, and others.',
    icon: 'bolt',
  },
  {
    title: 'Compact 60% Layout',
    description: '61 keys for maximum desk space and better movement freedom in games.',
    icon: 'keyboard',
  },
  {
    title: 'Customizable RGB',
    description: 'Multiple lighting effects configurable via dedicated software.',
    icon: 'lightbulb',
  },
  {
    title: 'USB-C Connection',
    description: 'Detachable cable for better durability and portability.',
    icon: 'usb',
  },
  {
    title: 'Ultra-Fast Response Time',
    description: 'Perfect for FPS, MOBA, and e-sports.',
    icon: 'tachometer-alt',
  },
  {
    title: 'Box Contents',
    description: 'GK61 keyboard, USB-C cable, keycap puller, switch puller, and manual.',
    icon: 'box-open',
  },
];
